/*
 * Circuit ID REST API
 *
 * # Introduction Circuit ID&reg; is an innovative cloud communications platform that redefines your connectivity experience. Our cutting-edge AI-powered solution seamlessly integrates calling, meetings, messaging, voicemail, fax, SIP Trunking, mobile broadband, and mobile phone services, accessible wherever you and your devices go.                  Whether you are a beginner getting started with our API or an experienced developer looking for advanced features, this documentation site will serve as your comprehensive guide.   We are excited to have you on board and are confident that this documentation site will empower you to leverage the full potential of our REST API.  If you have any questions or require further assistance, please don't hesitate to reach out to our support team.                  Happy coding!
 *
 * The version of the OpenAPI document: 0.47.19
 * Contact: support@circuitid.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.CircuitID.Api;
using Com.CircuitID.Models;
using Com.CircuitID.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.CircuitID.Test
{
    /// <summary>
    ///  Class for testing GetHoliday200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetHoliday200ResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetHoliday200Response
        //private GetHoliday200Response instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetHoliday200Response
            //instance = new GetHoliday200Response();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetHoliday200Response
        /// </summary>
        [Test]
        public void GetHoliday200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetHoliday200Response
            //Assert.IsInstanceOf(typeof(GetHoliday200Response), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
        /// <summary>
        /// Test the property 'ObjectRef'
        /// </summary>
        [Test]
        public void ObjectRefTest()
        {
            // TODO unit test for the property 'ObjectRef'
        }
        /// <summary>
        /// Test the property 'DateTimeRanges'
        /// </summary>
        [Test]
        public void DateTimeRangesTest()
        {
            // TODO unit test for the property 'DateTimeRanges'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'DestinationType'
        /// </summary>
        [Test]
        public void DestinationTypeTest()
        {
            // TODO unit test for the property 'DestinationType'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Test]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'Ref'
        /// </summary>
        [Test]
        public void RefTest()
        {
            // TODO unit test for the property 'Ref'
        }
        /// <summary>
        /// Test the property 'CallForwardingDestination'
        /// </summary>
        [Test]
        public void CallForwardingDestinationTest()
        {
            // TODO unit test for the property 'CallForwardingDestination'
        }
        /// <summary>
        /// Test the property 'CreatedByUserId'
        /// </summary>
        [Test]
        public void CreatedByUserIdTest()
        {
            // TODO unit test for the property 'CreatedByUserId'
        }
        /// <summary>
        /// Test the property 'UpdatedByUserId'
        /// </summary>
        [Test]
        public void UpdatedByUserIdTest()
        {
            // TODO unit test for the property 'UpdatedByUserId'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
